-- MySQL Script generated by MySQL Workbench
-- Wed Dec 21 22:41:35 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO` (
  `USUARIO_ID` INT NOT NULL AUTO_INCREMENT,
  `USUARIO_NOME` VARCHAR(45) NOT NULL,
  `USUARIO_SENHA` VARCHAR(45) NOT NULL,
  `USUARIO_EMAIL` VARCHAR(45) NOT NULL,
  `USUARIO_CPF` INT NOT NULL,
  `USUARIO_TEL` INT NOT NULL,
  PRIMARY KEY (`USUARIO_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TIPO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TIPO` (
  `TIPO_ID` INT NOT NULL AUTO_INCREMENT,
  `TIPO_DESCRICAO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TIPO_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OBJ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OBJ` (
  `OBJ_ID` INT NOT NULL AUTO_INCREMENT,
  `OBJ_DESCRICAO` VARCHAR(45) NOT NULL,
  `OBJ_IMG` VARCHAR(45) NOT NULL,
  `OBJ_TIPO_ID` INT NOT NULL,
  `OBJ_USUARIO_ID` INT NOT NULL,
  PRIMARY KEY (`OBJ_ID`),
  INDEX `fk_OBJ_TIPO1_idx` (`OBJ_TIPO_ID` ASC) VISIBLE,
  INDEX `fk_OBJ_USUARIO1_idx` (`OBJ_USUARIO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_OBJ_TIPO1`
    FOREIGN KEY (`OBJ_TIPO_ID`)
    REFERENCES `mydb`.`TIPO` (`TIPO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OBJ_USUARIO1`
    FOREIGN KEY (`OBJ_USUARIO_ID`)
    REFERENCES `mydb`.`USUARIO` (`USUARIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AGENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AGENDA` (
  `AGD_ID` INT NOT NULL AUTO_INCREMENT,
  `USUARIO_DOADOR_ID` INT NOT NULL,
  `USUARIO_RECEPTOR_ID` INT NOT NULL,
  `AGD_OBJ_ID` INT NOT NULL,
  `AGD_DATETIME` DATETIME NOT NULL,
  `AGD_CEP` INT NOT NULL,
  PRIMARY KEY (`AGD_ID`),
  INDEX `fk_USUARIO_has_OBJ_OBJ1_idx` (`AGD_OBJ_ID` ASC) VISIBLE,
  INDEX `fk_USUARIO_has_OBJ_USUARIO_idx` (`USUARIO_DOADOR_ID` ASC) VISIBLE,
  INDEX `fk_AGENDA_USUARIO1_idx` (`USUARIO_RECEPTOR_ID` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIO_has_OBJ_USUARIO`
    FOREIGN KEY (`USUARIO_DOADOR_ID`)
    REFERENCES `mydb`.`USUARIO` (`USUARIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIO_has_OBJ_OBJ1`
    FOREIGN KEY (`AGD_OBJ_ID`)
    REFERENCES `mydb`.`OBJ` (`OBJ_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AGENDA_USUARIO1`
    FOREIGN KEY (`USUARIO_RECEPTOR_ID`)
    REFERENCES `mydb`.`USUARIO` (`USUARIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
